### ISSUE TITLE
Trying to use your default REACT template and its throwing an error out of the box

### ISSUE THREAD

**Issue by cashewnutz** [uniswap-integration/uniswap-dapp-integration-monorepo#1]
uniswap-dapp-shared-logic.js:formatted:1 Uncaught (in promise) Error: invalid address (argument="address", value="0", code=INVALID_ARGUMENT, version=address/5.4.0)
    at Logger.makeError (uniswap-dapp-shared-logic.js:formatted:1)
    at Logger.throwError (uniswap-dapp-shared-logic.js:formatted:1)
    at Logger.throwArgumentError (uniswap-dapp-shared-logic.js:formatted:1)
    at Module.getAddress (uniswap-dapp-shared-logic.js:formatted:1)
    at getAddress (uniswap-dapp-shared-logic.js:formatted:1)
    at TokensFactoryPublic.TokensFactory.buildAllowanceAndBalanceContractCallContext (uniswap-dapp-shared-logic.js:formatted:1)
    at TokensFactoryPublic.<anonymous> (uniswap-dapp-shared-logic.js:formatted:1)
    at step (uniswap-dapp-shared-logic.js:formatted:1)
    at Object.next (uniswap-dapp-shared-logic.js:formatted:1)
    at uniswap-dapp-shared-logic.js:formatted:1
    at new Promise (<anonymous>)
    at push../node_modules/simple-uniswap-sdk/dist/esm/factories/token/tokens.factory.js.__awaiter (uniswap-dapp-shared-logic.js:formatted:1)
    at TokensFactoryPublic.TokensFactory.getAllowanceAndBalanceOfForContracts (uniswap-dapp-shared-logic.js:formatted:1)
    at UniswapDappSharedLogic.<anonymous> (uniswap-dapp-shared-logic.js:formatted:1)
    at step (uniswap-dapp-shared-logic.js:formatted:1)
    at Object.next (uniswap-dapp-shared-logic.js:formatted:1)
    at uniswap-dapp-shared-logic.js:formatted:1
    at new Promise (<anonymous>)
    at push../node_modules/uniswap-dapp-integration-shared/dist/esm/uniswap-dapp-shared-logic.js.__awaiter (uniswap-dapp-shared-logic.js:formatted:1)
    at UniswapDappSharedLogic.getBalances (uniswap-dapp-shared-logic.js:formatted:1)
    at UniswapDappSharedLogic.<anonymous> (uniswap-dapp-shared-logic.js:formatted:1)
    at step (uniswap-dapp-shared-logic.js:formatted:1)
    at Object.next (uniswap-dapp-shared-logic.js:formatted:1)
    at fulfilled (uniswap-dapp-shared-logic.js:formatted:1)

**Comment by joshstevens19** [comment]
Thanks for raising this!

have you done the provider part? a deployed react app is here > https://uniswap-dapp-integration.netlify.app/ which works with metamask! the error above ` Error: invalid address` seems like it can not get your ethereum address. Here is the deployed react code from the above link using the most recent package > https://github.com/uniswap-integration/uniswap-dapp-integration-monorepo/tree/master/integration-apps/uniswap-react-test-integration-app

if you want me to investigate il need to see how your integrating it as it sounds like a error your side from that error trace

Thanks

**Comment by cashewnutz** [comment]
Hey @joshstevens19  thanks for the quick reply. I am succesfully connected via metamask and i can see that my accounts array is populated, is there anything else i can check?

![image](https://user-images.githubusercontent.com/15163204/128388309-19a1c8bb-cb14-4f2d-8f00-bc2413d89c26.png)

**Comment by cashewnutz** [comment]
My integration is basically a copy of your example integration

**Comment by joshstevens19** [comment]
hmm the only thing that comes to mind is make sure your do not render any of the UI until `uniswapDappSharedLogicContext` is defined > https://github.com/uniswap-integration/uniswap-dapp-integration-monorepo/blob/master/integration-apps/uniswap-react-test-integration-app/src/App.tsx#L71 if that has not got a if there it will try to render before it has all the info

**Comment by joshstevens19** [comment]
also are you passing the ethereum provider in?

**Comment by cashewnutz** [comment]
Yeah I have a use effect that isn't setting context until accounts are set
up. I am using window.ethereum as provider like the example.

**Comment by cashewnutz** [comment]
Here is my implementation, i essentially copied your initial implementation and used it

![image](https://user-images.githubusercontent.com/15163204/128392542-5fa15c0c-06e5-4237-b38a-2be829badb4e.png)

**Comment by cashewnutz** [comment]
What's really weird is, that your demo app works for me. And I'm using the same metamask wallet for both. 

Also, I pulled down the code that is running the demo app and tried to run it but got a bunch of invalid use of react hooks errors

**Comment by joshstevens19** [comment]
Ahh I see your problem you got 2 effects, you can’t define the shared logic before the aync call requestAccounts has finished if you moved it all in 1 effect and don’t set that shared context until requestAccount has resolved it should work for you. 

Yes that example is using internal packages you need to solve with NPM link etc! But the above will fix it. Try it all in 1 effect with it all in the async call like my example. 

This is due to passing ethereum into the uniswap react without the account unlocked creates issue like the above. As it can take any ethereum provider we can’t do MetaMask logic aka it’s down to you as the dApp. 

Let me know if that works.

**Comment by cashewnutz** [comment]
I switched out the two effects and it still doesnt work my dude. Still getting the same error
![image](https://user-images.githubusercontent.com/15163204/128401469-fecd8fa1-b300-4d87-aee7-8e9593edc908.png)

This initial code still throws the same address not found error

**Comment by joshstevens19** [comment]
Lovely lol! what network you loading in at on MetaMask? il try your code out tomorrow but that code looks like it should work. I wonder if it’s on a case where the network different! Be great if you created a little repo with the exact code so I could run it and test my end. Think that’s the only way I’m going to spot the issue here. If you get a repo up il look tomorrow morning. Just let me know network your using etc! Very very odd that my app works! It probs be something simple but from just the code itself I can’t spot it.

**Comment by cashewnutz** [comment]
For sure thing i can do that for you man. Im using the ethereum main network as you probably can expect. 

Ill push my repo up and you can pull down and let me know

**Comment by cashewnutz** [comment]
https://github.com/jajones10s/UNISWAP_RECREATE

Link to repo

**Comment by joshstevens19** [comment]
Cheers mate il check it out in morning 👍

**Comment by cashewnutz** [comment]
Thanks bro  @joshstevens19  Also, nice Name

**Comment by joshstevens19** [comment]
Ok man this was my fault. `uniswap-dapp-integration-shared` depends on `simple-uniswap-sdk` which has a `^` on it this means when a new `simple-uniswap-sdk` is released it will install it on `uniswap-dapp-integration-shared`. I put in a breaking change and well it broke it! I have just published a new `uniswap-dapp-integration-shared` package version 1.0.3 which you will need to install.. i just pulled down your repo and installed it and boom it works:

![image](https://user-images.githubusercontent.com/18472422/128542335-5ed067ee-5c95-4b39-8369-1ecdd013bb56.png)

Sorry about that issue! as thought your code was fine was just my dependency issue. 

Let me know this solves it for you, will close for now.
Thanks

**Comment by cashewnutz** [comment]
Fuck yeah dude this is so good to hear.  Did you update your repo w the
appropriate version of the dependency!

**Comment by joshstevens19** [comment]
Yeah just download 1.0.3 of the peer dependency uniswap-dapp-integration-shared in your repo and it work mate
